[project]
name = "auto_loot"
version = "2.0.55"
authors = [{ name = "galqawala" }]
description = """\
Automatically picks up weapons and items with configurable options
"""
dependencies = ["ui_utils"]

[tool.sdkmod]
name = "AutoLoot"
version = "2.0.55"
supported_games = ["BL2", "TPS"]
license = {name = "GPL3", url = "https://choosealicense.com/licenses/gpl-3.0/" }
download = "https://github.com/galqawala/AutoLoot/raw/refs/heads/master/AutoLoot.sdkmod"