[project]
name = "autoloot"
version = "1.0.3"
authors = [{ name = "galqawala" }]
description = """\
Automatically picks up weapons and items with configurable options.

Features smart tracking to avoid re-picking items you've already seen or dropped.
"""

[project.urls]
Repository = "https://github.com/galqawala/AutoLoot"

[tool.sdkmod]
name = "AutoLoot"
license = {name = "MIT", url = "https://choosealicense.com/licenses/mit/" }
download = "https://raw.githubusercontent.com/galqawala/AutoLoot/refs/heads/master/autoloot.sdkmod"