[build-system]
requires = ["mods_base"]

[project]
name = "AutoLoot"
version = "2.0.1"
authors = [{name = "galqawala"}]
description = "Automatically picks up weapons and items with configurable options"
readme = {text = "Automatically picks up weapons and items with configurable options", content-type = "text/plain"}
requires-python = ">=3.11"
keywords = ["bl-sdk"]

[project.urls]
Repository = "https://github.com/bl-sdk/bl-sdk-mods"

[tool.mods_base]
requirements_txt_path = "requirements.txt"